export type EquipmentStatus = "UP" | "Partially UP" | "Down";

export type JobPriority = "High" | "Mid" | "Low";

export type RootCause =
  | "User error"
  | "Power supply"
  | "Software"
  | "Hardware"
  | "Consumable"
  | string;

export type Resolution =
  | "Calibration"
  | "Software reload"
  | "Hardware error"
  | "Accessory"
  | "End user training"
  | "Consumable"
  | string;

export type JobStatus = "In Progress" | "On Hold" | "Completed" | "Open" | "Pending Review";

export interface DebriefLabourRecord {
  startDate: string;
  endDate: string;
  travelStartTime: string;
  travelEndTime: string;
  labourStartTime: string;
  labourEndTime: string;
  workDone: string;
  equipmentStatus: EquipmentStatus;
  jobStatus: JobStatus;
  holdReason?: string; // e.g. "Awaiting Part"
  rootCause?: RootCause;
  resolution?: Resolution;
}

export interface DebriefPartUsed {
  id: string;
  partNumber: string;
  serialNumber?: string;
  description: string;
  modality?: string;
  oem?: string;
  model?: string;
  unitCost: number;
  quantityUsed: number;
  totalCost: number;
}

export type ExpenseType =
  | "Lodging"
  | "Transport (flight)"
  | "Transport (taxi)"
  | "Feeding";

export interface DebriefExpense {
  id: string;
  dateOfExpense: string;
  typeOfExpense: ExpenseType;
  receiptAvailable: boolean;
  receiptFileName?: string;
  receiptUrl?: string;
  note: string;
  expenseCode: string; // generated by finance team
  amount?: number;
}

export type DebriefDocumentType =
  | "Equipment checklist"
  | "Installation checklist"
  | "Delivery note"
  | "3rd party service report"
  | "Others";

export interface DebriefDocument {
  id: string;
  documentType: DebriefDocumentType;
  comment: string;
  fileName: string;
  fileUrl: string;
  fileSize?: string;
  uploadDate: string; // auto-generated, cannot be changed
}

export interface DebriefToolUsed {
  id: string;
  toolId: string; // tool code from tools module
  serialNumber: string;
  description: string;
  oem?: string;
  dateOfUse: string;
  calibrationDate: string;
  calibrationDueDate: string;
}

export interface DebriefJob {
  id: string;
  jobNumber: string; // System-generated e.g. "JOB-2026-0001"
  assetNumber: string; // e.g. "EQ-RAD-001"
  modality: string;
  oem: string;
  model: string;
  serialNumber: string;
  warrantyStartDate: string;
  warrantyEndDate: string;
  contractStartDate: string;
  contractEndDate: string;
  contractType?: string;
  yearOfManufacture: string;
  jobType: string;
  jobOpenDate: string;
  jobStartDate: string;
  equipmentStatus: EquipmentStatus;
  jobPriority: JobPriority;
  assignedToId: string;
  assignedToName: string;
  assistedByIds?: string[];
  assistedByNames?: string[];
  assistedBy?: string;
  complaintDate?: string;
  complaintTime?: string;
  contactName?: string;
  contactEmail?: string;
  location?: string;
  address?: string;
  reportedIssue?: string;
  startDate?: string;
  endDate?: string;
  rootCause?: RootCause;
  resolution?: Resolution;
  jobStatus: JobStatus;
  holdReason?: string;

  // 6 Job Workspace sections
  labour?: DebriefLabourRecord;
  partsUsed?: DebriefPartUsed[];
  expenses?: DebriefExpense[];
  documents?: DebriefDocument[];
  toolsUsed?: DebriefToolUsed[];

  createdAt: string;
  updatedAt: string;
}

export interface CreateJobInput {
  assetNumber: string;
  modality: string;
  oem: string;
  location: string;
  address: string;
  warrantyStartDate: string;
  warrantyEndDate: string;
  model: string;
  serialNumber: string;
  yearOfManufacture: string;
  equipmentStatus: EquipmentStatus;
  contractType: string;
  contractEndDate: string;
  jobType: string;
  jobOpenDate: string;
  complaintDate: string;
  complaintTime: string;
  contactName: string;
  contactEmail: string;
  assignedToId: string;
  assignedToName: string;
  assistedByIds?: string[];
  assistedByNames?: string[];
  jobEquipmentStatus?: EquipmentStatus;
  jobPriority: JobPriority;
  jobStartDate: string;
  endDate?: string;
  reportedIssue: string;
}
