export type EquipmentStatus = "UP" | "Partially UP" | "Down";

export type JobPriority = "High" | "Mid" | "Low";

export type RootCause =
  | "User error"
  | "Power supply"
  | "Software"
  | "Hardware"
  | "Consumable"
  | string;

export type Resolution =
  | "Calibration"
  | "Software reload"
  | "Hardware error"
  | "Accessory"
  | "End user training"
  | "Consumable"
  | string;

export type JobStatus = "In Progress" | "On Hold" | "Completed" | "Open" | "Pending Review";
export type JobStage = "assigned" | "traveling" | "working" | "on_hold" | "completed";

export interface DebriefLabourRecord {
  startDate: string;
  endDate: string;
  // Action-stamped times (ISO strings set by button press, not manual entry)
  travelStartTime?: string | undefined;
  travelEndTime?: string | undefined;
  labourStartTime?: string | undefined;
  labourEndTime?: string | undefined;
  travelDurationHours?: number | undefined;
  labourDurationHours?: number | undefined;
  workDone: string;
  equipmentStatus: EquipmentStatus;
  jobStatus: JobStatus;
  stage?: JobStage | undefined;
  holdReason?: string | undefined; // e.g. "Awaiting Part"
  rootCause?: RootCause | undefined;
  resolution?: Resolution | undefined;
  // Sign-off metadata
  clientSignoffName?: string | undefined;
  clientSignoffDesignation?: string | undefined;
  clientSignoffDate?: string | undefined;
  engineerSignoffDate?: string | undefined;
}

export interface DebriefPartUsed {
  id: string;
  partNumber: string;
  serialNumber?: string | undefined;
  description: string;
  modality?: string | undefined;
  oem?: string | undefined;
  model?: string | undefined;
  unitCost: number;
  quantityUsed: number;
  totalCost: number;
}

export type ExpenseType =
  | "Lodging"
  | "Transport (flight)"
  | "Transport (taxi)"
  | "Feeding";

export interface DebriefExpense {
  id: string;
  dateOfExpense: string;
  typeOfExpense: ExpenseType;
  receiptAvailable: boolean;
  receiptFileName?: string | undefined;
  receiptUrl?: string | undefined;
  note: string;
  expenseCode: string; // generated by finance team
  amount?: number | undefined;
}

export type DebriefDocumentType =
  | "Equipment checklist"
  | "Installation checklist"
  | "Delivery note"
  | "3rd party service report"
  | "Others";

export interface DebriefDocument {
  id: string;
  documentType: DebriefDocumentType;
  comment: string;
  fileName: string;
  fileUrl: string;
  fileSize?: string | undefined;
  uploadDate: string; // auto-generated, cannot be changed
}

export interface DebriefToolUsed {
  id: string;
  toolId: string; // tool code from tools module
  serialNumber: string;
  description: string;
  oem?: string | undefined;
  dateOfUse: string;
  calibrationDate: string;
  calibrationDueDate: string;
}

export interface DebriefJob {
  id: string;
  jobNumber: string; // System-generated e.g. "JOB-2026-0001"
  assetNumber: string; // e.g. "EQ-RAD-001"
  modality: string;
  oem: string;
  model: string;
  serialNumber: string;
  warrantyStartDate: string;
  warrantyEndDate: string;
  contractStartDate: string;
  contractEndDate: string;
  contractType?: string | undefined;
  yearOfManufacture: string;
  jobType: string;
  jobOpenDate: string;
  jobStartDate: string;
  equipmentStatus: EquipmentStatus;
  jobPriority: JobPriority;
  assignedToId: string;
  assignedToName: string;
  assistedByIds?: string[] | undefined;
  assistedByNames?: string[] | undefined;
  assistedBy?: string | undefined;
  complaintDate?: string | undefined;
  complaintTime?: string | undefined;
  contactName?: string | undefined;
  contactEmail?: string | undefined;
  location?: string | undefined;
  address?: string | undefined;
  reportedIssue?: string | undefined;
  startDate?: string | undefined;
  endDate?: string | undefined;
  rootCause?: RootCause | undefined;
  resolution?: Resolution | undefined;
  jobStatus: JobStatus;
  stage?: JobStage | undefined;
  holdReason?: string | undefined;

  // Financial Rollup
  totalPartsCost?: number | undefined;
  totalExpensesCost?: number | undefined;
  totalJobCost?: number | undefined;

  // Sign-off Acknowledgement
  clientSignoffName?: string | undefined;
  clientSignoffDesignation?: string | undefined;
  clientSignoffDate?: string | undefined;
  engineerSignoffDate?: string | undefined;

  // 6 Job Workspace sections
  labour?: DebriefLabourRecord | undefined;
  partsUsed?: DebriefPartUsed[] | undefined;
  expenses?: DebriefExpense[] | undefined;
  documents?: DebriefDocument[] | undefined;
  toolsUsed?: DebriefToolUsed[] | undefined;

  createdAt: string;
  updatedAt: string;
}

export interface CreateJobInput {
  assetNumber: string;
  modality: string;
  oem: string;
  location: string;
  address: string;
  warrantyStartDate: string;
  warrantyEndDate: string;
  model: string;
  serialNumber: string;
  yearOfManufacture: string;
  equipmentStatus: EquipmentStatus;
  contractType: string;
  contractEndDate: string;
  jobType: string;
  jobOpenDate: string;
  complaintDate: string;
  complaintTime: string;
  contactName: string;
  contactEmail: string;
  assignedToId: string;
  assignedToName: string;
  assistedByIds?: string[];
  assistedByNames?: string[];
  jobEquipmentStatus?: EquipmentStatus;
  jobPriority: JobPriority;
  jobStartDate: string;
  endDate?: string;
  reportedIssue: string;
}
