/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppDebriefRouteImport } from './routes/app.debrief'
import { Route as AppFinancialRouteImport } from './routes/app.financial'
import { Route as AppManagementRouteImport } from './routes/app.management'
import { Route as AppPartsRouteImport } from './routes/app.parts'
import { Route as AppQualityRouteImport } from './routes/app.quality'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppToolsRouteImport } from './routes/app.tools'
import { Route as AppAssetsIndexRouteImport } from './routes/app.assets.index'
import { Route as AppAssetsContractsRouteImport } from './routes/app.assets.contracts'
import { Route as AppAssetsContractsDashboardRouteImport } from './routes/app.assets.contracts-dashboard'
import { Route as AppAssetsDashboardRouteImport } from './routes/app.assets.dashboard'
import { Route as AppAssetsListRouteImport } from './routes/app.assets.list'
import { Route as AppDebriefIndexRouteImport } from './routes/app.debrief.index'
import { Route as AppDebriefDashboardRouteImport } from './routes/app.debrief.dashboard'
import { Route as AppDebriefMyWorkRouteImport } from './routes/app.debrief.my-work'
import { Route as AppDebriefScheduleRouteImport } from './routes/app.debrief.schedule'
import { Route as AppDebriefWorkforceRouteImport } from './routes/app.debrief.workforce'
import { Route as AppFinancialIndexRouteImport } from './routes/app.financial.index'
import { Route as AppFinancialDashboardRouteImport } from './routes/app.financial.dashboard'
import { Route as AppFinancialOrdersRouteImport } from './routes/app.financial.orders'
import { Route as AppFinancialPurchaseOrdersRouteImport } from './routes/app.financial.purchase-orders'
import { Route as AppFinancialServiceContractsRouteImport } from './routes/app.financial.service-contracts'
import { Route as AppManagementIndexRouteImport } from './routes/app.management.index'
import { Route as AppManagementAssetsRouteImport } from './routes/app.management.assets'
import { Route as AppManagementContractsRouteImport } from './routes/app.management.contracts'
import { Route as AppManagementDebriefRouteImport } from './routes/app.management.debrief'
import { Route as AppManagementFinancialRouteImport } from './routes/app.management.financial'
import { Route as AppManagementPartsRouteImport } from './routes/app.management.parts'
import { Route as AppManagementQualityRouteImport } from './routes/app.management.quality'
import { Route as AppManagementToolsRouteImport } from './routes/app.management.tools'
import { Route as AppPartsIndexRouteImport } from './routes/app.parts.index'
import { Route as AppPartsAuditRouteImport } from './routes/app.parts.audit'
import { Route as AppPartsDashboardRouteImport } from './routes/app.parts.dashboard'
import { Route as AppPartsListRouteImport } from './routes/app.parts.list'
import { Route as AppPartsMovementsRouteImport } from './routes/app.parts.movements'
import { Route as AppQualityIndexRouteImport } from './routes/app.quality.index'
import { Route as AppQualityApprovalsRouteImport } from './routes/app.quality.approvals'
import { Route as AppQualityArchiveRouteImport } from './routes/app.quality.archive'
import { Route as AppQualityChecklistsRouteImport } from './routes/app.quality.checklists'
import { Route as AppQualityDashboardRouteImport } from './routes/app.quality.dashboard'
import { Route as AppQualityMyTasksRouteImport } from './routes/app.quality.my-tasks'
import { Route as AppQualityPolicyDocumentsRouteImport } from './routes/app.quality.policy-documents'
import { Route as AppQualityReviewsRouteImport } from './routes/app.quality.reviews'
import { Route as AppQualityTrainingRouteImport } from './routes/app.quality.training'
import { Route as AppSettingsIndexRouteImport } from './routes/app.settings.index'
import { Route as AppSettingsAuditLogRouteImport } from './routes/app.settings.audit-log'
import { Route as AppSettingsDashboardRouteImport } from './routes/app.settings.dashboard'
import { Route as AppSettingsDebriefRouteImport } from './routes/app.settings.debrief'
import { Route as AppSettingsPartsInventoryRouteImport } from './routes/app.settings.parts-inventory'
import { Route as AppSettingsPersonnelRouteImport } from './routes/app.settings.personnel'
import { Route as AppSettingsQualityRouteImport } from './routes/app.settings.quality'
import { Route as AppSettingsToolsRouteImport } from './routes/app.settings.tools'
import { Route as AppSettingsTrainingRouteImport } from './routes/app.settings.training'
import { Route as AppSettingsUserAccountsRouteImport } from './routes/app.settings.user-accounts'
import { Route as AppToolsIndexRouteImport } from './routes/app.tools.index'
import { Route as AppToolsToolIdRouteImport } from './routes/app.tools.$toolId'
import { Route as AppToolsArchivedJobsRouteImport } from './routes/app.tools.archived-jobs'
import { Route as AppToolsArchivedToolsRouteImport } from './routes/app.tools.archived-tools'
import { Route as AppToolsCalibrationRouteImport } from './routes/app.tools.calibration'
import { Route as AppToolsDashboardRouteImport } from './routes/app.tools.dashboard'
import { Route as AppToolsDocumentsRouteImport } from './routes/app.tools.documents'
import { Route as AppToolsExpenseApprovalsRouteImport } from './routes/app.tools.expense-approvals'
import { Route as AppToolsMyExpensesRouteImport } from './routes/app.tools.my-expenses'
import { Route as AppToolsMyJobsRouteImport } from './routes/app.tools.my-jobs'
import { Route as AppDebriefWorkspaceJobIdRouteImport } from './routes/app.debrief.workspace.$jobId'
import { Route as AppToolsJobsIndexRouteImport } from './routes/app.tools.jobs.index'
import { Route as AppToolsJobsJobIdRouteImport } from './routes/app.tools.jobs.$jobId'
import { Route as AppToolsJobsCreateRouteImport } from './routes/app.tools.jobs.create'
import { Route as AppToolsJobsOpenRouteImport } from './routes/app.tools.jobs.open'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppDebriefRoute = AppDebriefRouteImport.update({
  id: '/debrief',
  path: '/debrief',
  getParentRoute: () => AppRoute,
} as any)
const AppFinancialRoute = AppFinancialRouteImport.update({
  id: '/financial',
  path: '/financial',
  getParentRoute: () => AppRoute,
} as any)
const AppManagementRoute = AppManagementRouteImport.update({
  id: '/management',
  path: '/management',
  getParentRoute: () => AppRoute,
} as any)
const AppPartsRoute = AppPartsRouteImport.update({
  id: '/parts',
  path: '/parts',
  getParentRoute: () => AppRoute,
} as any)
const AppQualityRoute = AppQualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppToolsRoute = AppToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AppRoute,
} as any)
const AppAssetsIndexRoute = AppAssetsIndexRouteImport.update({
  id: '/assets/',
  path: '/assets/',
  getParentRoute: () => AppRoute,
} as any)
const AppAssetsContractsRoute = AppAssetsContractsRouteImport.update({
  id: '/assets/contracts',
  path: '/assets/contracts',
  getParentRoute: () => AppRoute,
} as any)
const AppAssetsContractsDashboardRoute =
  AppAssetsContractsDashboardRouteImport.update({
    id: '/assets/contracts-dashboard',
    path: '/assets/contracts-dashboard',
    getParentRoute: () => AppRoute,
  } as any)
const AppAssetsDashboardRoute = AppAssetsDashboardRouteImport.update({
  id: '/assets/dashboard',
  path: '/assets/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAssetsListRoute = AppAssetsListRouteImport.update({
  id: '/assets/list',
  path: '/assets/list',
  getParentRoute: () => AppRoute,
} as any)
const AppDebriefIndexRoute = AppDebriefIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDebriefRoute,
} as any)
const AppDebriefDashboardRoute = AppDebriefDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppDebriefRoute,
} as any)
const AppDebriefMyWorkRoute = AppDebriefMyWorkRouteImport.update({
  id: '/my-work',
  path: '/my-work',
  getParentRoute: () => AppDebriefRoute,
} as any)
const AppDebriefScheduleRoute = AppDebriefScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AppDebriefRoute,
} as any)
const AppDebriefWorkforceRoute = AppDebriefWorkforceRouteImport.update({
  id: '/workforce',
  path: '/workforce',
  getParentRoute: () => AppDebriefRoute,
} as any)
const AppFinancialIndexRoute = AppFinancialIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppFinancialRoute,
} as any)
const AppFinancialDashboardRoute = AppFinancialDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppFinancialRoute,
} as any)
const AppFinancialOrdersRoute = AppFinancialOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AppFinancialRoute,
} as any)
const AppFinancialPurchaseOrdersRoute =
  AppFinancialPurchaseOrdersRouteImport.update({
    id: '/purchase-orders',
    path: '/purchase-orders',
    getParentRoute: () => AppFinancialRoute,
  } as any)
const AppFinancialServiceContractsRoute =
  AppFinancialServiceContractsRouteImport.update({
    id: '/service-contracts',
    path: '/service-contracts',
    getParentRoute: () => AppFinancialRoute,
  } as any)
const AppManagementIndexRoute = AppManagementIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppManagementRoute,
} as any)
const AppManagementAssetsRoute = AppManagementAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => AppManagementRoute,
} as any)
const AppManagementContractsRoute = AppManagementContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => AppManagementRoute,
} as any)
const AppManagementDebriefRoute = AppManagementDebriefRouteImport.update({
  id: '/debrief',
  path: '/debrief',
  getParentRoute: () => AppManagementRoute,
} as any)
const AppManagementFinancialRoute = AppManagementFinancialRouteImport.update({
  id: '/financial',
  path: '/financial',
  getParentRoute: () => AppManagementRoute,
} as any)
const AppManagementPartsRoute = AppManagementPartsRouteImport.update({
  id: '/parts',
  path: '/parts',
  getParentRoute: () => AppManagementRoute,
} as any)
const AppManagementQualityRoute = AppManagementQualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => AppManagementRoute,
} as any)
const AppManagementToolsRoute = AppManagementToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AppManagementRoute,
} as any)
const AppPartsIndexRoute = AppPartsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPartsRoute,
} as any)
const AppPartsAuditRoute = AppPartsAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppPartsRoute,
} as any)
const AppPartsDashboardRoute = AppPartsDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppPartsRoute,
} as any)
const AppPartsListRoute = AppPartsListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => AppPartsRoute,
} as any)
const AppPartsMovementsRoute = AppPartsMovementsRouteImport.update({
  id: '/movements',
  path: '/movements',
  getParentRoute: () => AppPartsRoute,
} as any)
const AppQualityIndexRoute = AppQualityIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppQualityRoute,
} as any)
const AppQualityApprovalsRoute = AppQualityApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AppQualityRoute,
} as any)
const AppQualityArchiveRoute = AppQualityArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => AppQualityRoute,
} as any)
const AppQualityChecklistsRoute = AppQualityChecklistsRouteImport.update({
  id: '/checklists',
  path: '/checklists',
  getParentRoute: () => AppQualityRoute,
} as any)
const AppQualityDashboardRoute = AppQualityDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppQualityRoute,
} as any)
const AppQualityMyTasksRoute = AppQualityMyTasksRouteImport.update({
  id: '/my-tasks',
  path: '/my-tasks',
  getParentRoute: () => AppQualityRoute,
} as any)
const AppQualityPolicyDocumentsRoute =
  AppQualityPolicyDocumentsRouteImport.update({
    id: '/policy-documents',
    path: '/policy-documents',
    getParentRoute: () => AppQualityRoute,
  } as any)
const AppQualityReviewsRoute = AppQualityReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AppQualityRoute,
} as any)
const AppQualityTrainingRoute = AppQualityTrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => AppQualityRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsAuditLogRoute = AppSettingsAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsDashboardRoute = AppSettingsDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsDebriefRoute = AppSettingsDebriefRouteImport.update({
  id: '/debrief',
  path: '/debrief',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsPartsInventoryRoute =
  AppSettingsPartsInventoryRouteImport.update({
    id: '/parts-inventory',
    path: '/parts-inventory',
    getParentRoute: () => AppSettingsRoute,
  } as any)
const AppSettingsPersonnelRoute = AppSettingsPersonnelRouteImport.update({
  id: '/personnel',
  path: '/personnel',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsQualityRoute = AppSettingsQualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsToolsRoute = AppSettingsToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsTrainingRoute = AppSettingsTrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsUserAccountsRoute = AppSettingsUserAccountsRouteImport.update({
  id: '/user-accounts',
  path: '/user-accounts',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppToolsIndexRoute = AppToolsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppToolsRoute,
} as any)
const AppToolsToolIdRoute = AppToolsToolIdRouteImport.update({
  id: '/$toolId',
  path: '/$toolId',
  getParentRoute: () => AppToolsRoute,
} as any)
const AppToolsArchivedJobsRoute = AppToolsArchivedJobsRouteImport.update({
  id: '/archived-jobs',
  path: '/archived-jobs',
  getParentRoute: () => AppToolsRoute,
} as any)
const AppToolsArchivedToolsRoute = AppToolsArchivedToolsRouteImport.update({
  id: '/archived-tools',
  path: '/archived-tools',
  getParentRoute: () => AppToolsRoute,
} as any)
const AppToolsCalibrationRoute = AppToolsCalibrationRouteImport.update({
  id: '/calibration',
  path: '/calibration',
  getParentRoute: () => AppToolsRoute,
} as any)
const AppToolsDashboardRoute = AppToolsDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppToolsRoute,
} as any)
const AppToolsDocumentsRoute = AppToolsDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppToolsRoute,
} as any)
const AppToolsExpenseApprovalsRoute =
  AppToolsExpenseApprovalsRouteImport.update({
    id: '/expense-approvals',
    path: '/expense-approvals',
    getParentRoute: () => AppToolsRoute,
  } as any)
const AppToolsMyExpensesRoute = AppToolsMyExpensesRouteImport.update({
  id: '/my-expenses',
  path: '/my-expenses',
  getParentRoute: () => AppToolsRoute,
} as any)
const AppToolsMyJobsRoute = AppToolsMyJobsRouteImport.update({
  id: '/my-jobs',
  path: '/my-jobs',
  getParentRoute: () => AppToolsRoute,
} as any)
const AppDebriefWorkspaceJobIdRoute =
  AppDebriefWorkspaceJobIdRouteImport.update({
    id: '/workspace/$jobId',
    path: '/workspace/$jobId',
    getParentRoute: () => AppDebriefRoute,
  } as any)
const AppToolsJobsIndexRoute = AppToolsJobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => AppToolsRoute,
} as any)
const AppToolsJobsJobIdRoute = AppToolsJobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => AppToolsRoute,
} as any)
const AppToolsJobsCreateRoute = AppToolsJobsCreateRouteImport.update({
  id: '/jobs/create',
  path: '/jobs/create',
  getParentRoute: () => AppToolsRoute,
} as any)
const AppToolsJobsOpenRoute = AppToolsJobsOpenRouteImport.update({
  id: '/jobs/open',
  path: '/jobs/open',
  getParentRoute: () => AppToolsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/debrief': typeof AppDebriefRouteWithChildren
  '/app/financial': typeof AppFinancialRouteWithChildren
  '/app/management': typeof AppManagementRouteWithChildren
  '/app/parts': typeof AppPartsRouteWithChildren
  '/app/quality': typeof AppQualityRouteWithChildren
  '/app/settings': typeof AppSettingsRouteWithChildren
  '/app/tools': typeof AppToolsRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/assets/contracts': typeof AppAssetsContractsRoute
  '/app/assets/contracts-dashboard': typeof AppAssetsContractsDashboardRoute
  '/app/assets/dashboard': typeof AppAssetsDashboardRoute
  '/app/assets/list': typeof AppAssetsListRoute
  '/app/debrief/dashboard': typeof AppDebriefDashboardRoute
  '/app/debrief/my-work': typeof AppDebriefMyWorkRoute
  '/app/debrief/schedule': typeof AppDebriefScheduleRoute
  '/app/debrief/workforce': typeof AppDebriefWorkforceRoute
  '/app/financial/dashboard': typeof AppFinancialDashboardRoute
  '/app/financial/orders': typeof AppFinancialOrdersRoute
  '/app/financial/purchase-orders': typeof AppFinancialPurchaseOrdersRoute
  '/app/financial/service-contracts': typeof AppFinancialServiceContractsRoute
  '/app/management/assets': typeof AppManagementAssetsRoute
  '/app/management/contracts': typeof AppManagementContractsRoute
  '/app/management/debrief': typeof AppManagementDebriefRoute
  '/app/management/financial': typeof AppManagementFinancialRoute
  '/app/management/parts': typeof AppManagementPartsRoute
  '/app/management/quality': typeof AppManagementQualityRoute
  '/app/management/tools': typeof AppManagementToolsRoute
  '/app/parts/audit': typeof AppPartsAuditRoute
  '/app/parts/dashboard': typeof AppPartsDashboardRoute
  '/app/parts/list': typeof AppPartsListRoute
  '/app/parts/movements': typeof AppPartsMovementsRoute
  '/app/quality/approvals': typeof AppQualityApprovalsRoute
  '/app/quality/archive': typeof AppQualityArchiveRoute
  '/app/quality/checklists': typeof AppQualityChecklistsRoute
  '/app/quality/dashboard': typeof AppQualityDashboardRoute
  '/app/quality/my-tasks': typeof AppQualityMyTasksRoute
  '/app/quality/policy-documents': typeof AppQualityPolicyDocumentsRoute
  '/app/quality/reviews': typeof AppQualityReviewsRoute
  '/app/quality/training': typeof AppQualityTrainingRoute
  '/app/settings/audit-log': typeof AppSettingsAuditLogRoute
  '/app/settings/dashboard': typeof AppSettingsDashboardRoute
  '/app/settings/debrief': typeof AppSettingsDebriefRoute
  '/app/settings/parts-inventory': typeof AppSettingsPartsInventoryRoute
  '/app/settings/personnel': typeof AppSettingsPersonnelRoute
  '/app/settings/quality': typeof AppSettingsQualityRoute
  '/app/settings/tools': typeof AppSettingsToolsRoute
  '/app/settings/training': typeof AppSettingsTrainingRoute
  '/app/settings/user-accounts': typeof AppSettingsUserAccountsRoute
  '/app/tools/$toolId': typeof AppToolsToolIdRoute
  '/app/tools/archived-jobs': typeof AppToolsArchivedJobsRoute
  '/app/tools/archived-tools': typeof AppToolsArchivedToolsRoute
  '/app/tools/calibration': typeof AppToolsCalibrationRoute
  '/app/tools/dashboard': typeof AppToolsDashboardRoute
  '/app/tools/documents': typeof AppToolsDocumentsRoute
  '/app/tools/expense-approvals': typeof AppToolsExpenseApprovalsRoute
  '/app/tools/my-expenses': typeof AppToolsMyExpensesRoute
  '/app/tools/my-jobs': typeof AppToolsMyJobsRoute
  '/app/assets/': typeof AppAssetsIndexRoute
  '/app/debrief/': typeof AppDebriefIndexRoute
  '/app/financial/': typeof AppFinancialIndexRoute
  '/app/management/': typeof AppManagementIndexRoute
  '/app/parts/': typeof AppPartsIndexRoute
  '/app/quality/': typeof AppQualityIndexRoute
  '/app/settings/': typeof AppSettingsIndexRoute
  '/app/tools/': typeof AppToolsIndexRoute
  '/app/debrief/workspace/$jobId': typeof AppDebriefWorkspaceJobIdRoute
  '/app/tools/jobs/$jobId': typeof AppToolsJobsJobIdRoute
  '/app/tools/jobs/create': typeof AppToolsJobsCreateRoute
  '/app/tools/jobs/open': typeof AppToolsJobsOpenRoute
  '/app/tools/jobs/': typeof AppToolsJobsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app': typeof AppIndexRoute
  '/app/assets/contracts': typeof AppAssetsContractsRoute
  '/app/assets/contracts-dashboard': typeof AppAssetsContractsDashboardRoute
  '/app/assets/dashboard': typeof AppAssetsDashboardRoute
  '/app/assets/list': typeof AppAssetsListRoute
  '/app/debrief/dashboard': typeof AppDebriefDashboardRoute
  '/app/debrief/my-work': typeof AppDebriefMyWorkRoute
  '/app/debrief/schedule': typeof AppDebriefScheduleRoute
  '/app/debrief/workforce': typeof AppDebriefWorkforceRoute
  '/app/financial/dashboard': typeof AppFinancialDashboardRoute
  '/app/financial/orders': typeof AppFinancialOrdersRoute
  '/app/financial/purchase-orders': typeof AppFinancialPurchaseOrdersRoute
  '/app/financial/service-contracts': typeof AppFinancialServiceContractsRoute
  '/app/management/assets': typeof AppManagementAssetsRoute
  '/app/management/contracts': typeof AppManagementContractsRoute
  '/app/management/debrief': typeof AppManagementDebriefRoute
  '/app/management/financial': typeof AppManagementFinancialRoute
  '/app/management/parts': typeof AppManagementPartsRoute
  '/app/management/quality': typeof AppManagementQualityRoute
  '/app/management/tools': typeof AppManagementToolsRoute
  '/app/parts/audit': typeof AppPartsAuditRoute
  '/app/parts/dashboard': typeof AppPartsDashboardRoute
  '/app/parts/list': typeof AppPartsListRoute
  '/app/parts/movements': typeof AppPartsMovementsRoute
  '/app/quality/approvals': typeof AppQualityApprovalsRoute
  '/app/quality/archive': typeof AppQualityArchiveRoute
  '/app/quality/checklists': typeof AppQualityChecklistsRoute
  '/app/quality/dashboard': typeof AppQualityDashboardRoute
  '/app/quality/my-tasks': typeof AppQualityMyTasksRoute
  '/app/quality/policy-documents': typeof AppQualityPolicyDocumentsRoute
  '/app/quality/reviews': typeof AppQualityReviewsRoute
  '/app/quality/training': typeof AppQualityTrainingRoute
  '/app/settings/audit-log': typeof AppSettingsAuditLogRoute
  '/app/settings/dashboard': typeof AppSettingsDashboardRoute
  '/app/settings/debrief': typeof AppSettingsDebriefRoute
  '/app/settings/parts-inventory': typeof AppSettingsPartsInventoryRoute
  '/app/settings/personnel': typeof AppSettingsPersonnelRoute
  '/app/settings/quality': typeof AppSettingsQualityRoute
  '/app/settings/tools': typeof AppSettingsToolsRoute
  '/app/settings/training': typeof AppSettingsTrainingRoute
  '/app/settings/user-accounts': typeof AppSettingsUserAccountsRoute
  '/app/tools/$toolId': typeof AppToolsToolIdRoute
  '/app/tools/archived-jobs': typeof AppToolsArchivedJobsRoute
  '/app/tools/archived-tools': typeof AppToolsArchivedToolsRoute
  '/app/tools/calibration': typeof AppToolsCalibrationRoute
  '/app/tools/dashboard': typeof AppToolsDashboardRoute
  '/app/tools/documents': typeof AppToolsDocumentsRoute
  '/app/tools/expense-approvals': typeof AppToolsExpenseApprovalsRoute
  '/app/tools/my-expenses': typeof AppToolsMyExpensesRoute
  '/app/tools/my-jobs': typeof AppToolsMyJobsRoute
  '/app/assets': typeof AppAssetsIndexRoute
  '/app/debrief': typeof AppDebriefIndexRoute
  '/app/financial': typeof AppFinancialIndexRoute
  '/app/management': typeof AppManagementIndexRoute
  '/app/parts': typeof AppPartsIndexRoute
  '/app/quality': typeof AppQualityIndexRoute
  '/app/settings': typeof AppSettingsIndexRoute
  '/app/tools': typeof AppToolsIndexRoute
  '/app/debrief/workspace/$jobId': typeof AppDebriefWorkspaceJobIdRoute
  '/app/tools/jobs/$jobId': typeof AppToolsJobsJobIdRoute
  '/app/tools/jobs/create': typeof AppToolsJobsCreateRoute
  '/app/tools/jobs/open': typeof AppToolsJobsOpenRoute
  '/app/tools/jobs': typeof AppToolsJobsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/debrief': typeof AppDebriefRouteWithChildren
  '/app/financial': typeof AppFinancialRouteWithChildren
  '/app/management': typeof AppManagementRouteWithChildren
  '/app/parts': typeof AppPartsRouteWithChildren
  '/app/quality': typeof AppQualityRouteWithChildren
  '/app/settings': typeof AppSettingsRouteWithChildren
  '/app/tools': typeof AppToolsRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/assets/contracts': typeof AppAssetsContractsRoute
  '/app/assets/contracts-dashboard': typeof AppAssetsContractsDashboardRoute
  '/app/assets/dashboard': typeof AppAssetsDashboardRoute
  '/app/assets/list': typeof AppAssetsListRoute
  '/app/debrief/dashboard': typeof AppDebriefDashboardRoute
  '/app/debrief/my-work': typeof AppDebriefMyWorkRoute
  '/app/debrief/schedule': typeof AppDebriefScheduleRoute
  '/app/debrief/workforce': typeof AppDebriefWorkforceRoute
  '/app/financial/dashboard': typeof AppFinancialDashboardRoute
  '/app/financial/orders': typeof AppFinancialOrdersRoute
  '/app/financial/purchase-orders': typeof AppFinancialPurchaseOrdersRoute
  '/app/financial/service-contracts': typeof AppFinancialServiceContractsRoute
  '/app/management/assets': typeof AppManagementAssetsRoute
  '/app/management/contracts': typeof AppManagementContractsRoute
  '/app/management/debrief': typeof AppManagementDebriefRoute
  '/app/management/financial': typeof AppManagementFinancialRoute
  '/app/management/parts': typeof AppManagementPartsRoute
  '/app/management/quality': typeof AppManagementQualityRoute
  '/app/management/tools': typeof AppManagementToolsRoute
  '/app/parts/audit': typeof AppPartsAuditRoute
  '/app/parts/dashboard': typeof AppPartsDashboardRoute
  '/app/parts/list': typeof AppPartsListRoute
  '/app/parts/movements': typeof AppPartsMovementsRoute
  '/app/quality/approvals': typeof AppQualityApprovalsRoute
  '/app/quality/archive': typeof AppQualityArchiveRoute
  '/app/quality/checklists': typeof AppQualityChecklistsRoute
  '/app/quality/dashboard': typeof AppQualityDashboardRoute
  '/app/quality/my-tasks': typeof AppQualityMyTasksRoute
  '/app/quality/policy-documents': typeof AppQualityPolicyDocumentsRoute
  '/app/quality/reviews': typeof AppQualityReviewsRoute
  '/app/quality/training': typeof AppQualityTrainingRoute
  '/app/settings/audit-log': typeof AppSettingsAuditLogRoute
  '/app/settings/dashboard': typeof AppSettingsDashboardRoute
  '/app/settings/debrief': typeof AppSettingsDebriefRoute
  '/app/settings/parts-inventory': typeof AppSettingsPartsInventoryRoute
  '/app/settings/personnel': typeof AppSettingsPersonnelRoute
  '/app/settings/quality': typeof AppSettingsQualityRoute
  '/app/settings/tools': typeof AppSettingsToolsRoute
  '/app/settings/training': typeof AppSettingsTrainingRoute
  '/app/settings/user-accounts': typeof AppSettingsUserAccountsRoute
  '/app/tools/$toolId': typeof AppToolsToolIdRoute
  '/app/tools/archived-jobs': typeof AppToolsArchivedJobsRoute
  '/app/tools/archived-tools': typeof AppToolsArchivedToolsRoute
  '/app/tools/calibration': typeof AppToolsCalibrationRoute
  '/app/tools/dashboard': typeof AppToolsDashboardRoute
  '/app/tools/documents': typeof AppToolsDocumentsRoute
  '/app/tools/expense-approvals': typeof AppToolsExpenseApprovalsRoute
  '/app/tools/my-expenses': typeof AppToolsMyExpensesRoute
  '/app/tools/my-jobs': typeof AppToolsMyJobsRoute
  '/app/assets/': typeof AppAssetsIndexRoute
  '/app/debrief/': typeof AppDebriefIndexRoute
  '/app/financial/': typeof AppFinancialIndexRoute
  '/app/management/': typeof AppManagementIndexRoute
  '/app/parts/': typeof AppPartsIndexRoute
  '/app/quality/': typeof AppQualityIndexRoute
  '/app/settings/': typeof AppSettingsIndexRoute
  '/app/tools/': typeof AppToolsIndexRoute
  '/app/debrief/workspace/$jobId': typeof AppDebriefWorkspaceJobIdRoute
  '/app/tools/jobs/$jobId': typeof AppToolsJobsJobIdRoute
  '/app/tools/jobs/create': typeof AppToolsJobsCreateRoute
  '/app/tools/jobs/open': typeof AppToolsJobsOpenRoute
  '/app/tools/jobs/': typeof AppToolsJobsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/debrief'
    | '/app/financial'
    | '/app/management'
    | '/app/parts'
    | '/app/quality'
    | '/app/settings'
    | '/app/tools'
    | '/app/'
    | '/app/assets/contracts'
    | '/app/assets/contracts-dashboard'
    | '/app/assets/dashboard'
    | '/app/assets/list'
    | '/app/debrief/dashboard'
    | '/app/debrief/my-work'
    | '/app/debrief/schedule'
    | '/app/debrief/workforce'
    | '/app/financial/dashboard'
    | '/app/financial/orders'
    | '/app/financial/purchase-orders'
    | '/app/financial/service-contracts'
    | '/app/management/assets'
    | '/app/management/contracts'
    | '/app/management/debrief'
    | '/app/management/financial'
    | '/app/management/parts'
    | '/app/management/quality'
    | '/app/management/tools'
    | '/app/parts/audit'
    | '/app/parts/dashboard'
    | '/app/parts/list'
    | '/app/parts/movements'
    | '/app/quality/approvals'
    | '/app/quality/archive'
    | '/app/quality/checklists'
    | '/app/quality/dashboard'
    | '/app/quality/my-tasks'
    | '/app/quality/policy-documents'
    | '/app/quality/reviews'
    | '/app/quality/training'
    | '/app/settings/audit-log'
    | '/app/settings/dashboard'
    | '/app/settings/debrief'
    | '/app/settings/parts-inventory'
    | '/app/settings/personnel'
    | '/app/settings/quality'
    | '/app/settings/tools'
    | '/app/settings/training'
    | '/app/settings/user-accounts'
    | '/app/tools/$toolId'
    | '/app/tools/archived-jobs'
    | '/app/tools/archived-tools'
    | '/app/tools/calibration'
    | '/app/tools/dashboard'
    | '/app/tools/documents'
    | '/app/tools/expense-approvals'
    | '/app/tools/my-expenses'
    | '/app/tools/my-jobs'
    | '/app/assets/'
    | '/app/debrief/'
    | '/app/financial/'
    | '/app/management/'
    | '/app/parts/'
    | '/app/quality/'
    | '/app/settings/'
    | '/app/tools/'
    | '/app/debrief/workspace/$jobId'
    | '/app/tools/jobs/$jobId'
    | '/app/tools/jobs/create'
    | '/app/tools/jobs/open'
    | '/app/tools/jobs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app'
    | '/app/assets/contracts'
    | '/app/assets/contracts-dashboard'
    | '/app/assets/dashboard'
    | '/app/assets/list'
    | '/app/debrief/dashboard'
    | '/app/debrief/my-work'
    | '/app/debrief/schedule'
    | '/app/debrief/workforce'
    | '/app/financial/dashboard'
    | '/app/financial/orders'
    | '/app/financial/purchase-orders'
    | '/app/financial/service-contracts'
    | '/app/management/assets'
    | '/app/management/contracts'
    | '/app/management/debrief'
    | '/app/management/financial'
    | '/app/management/parts'
    | '/app/management/quality'
    | '/app/management/tools'
    | '/app/parts/audit'
    | '/app/parts/dashboard'
    | '/app/parts/list'
    | '/app/parts/movements'
    | '/app/quality/approvals'
    | '/app/quality/archive'
    | '/app/quality/checklists'
    | '/app/quality/dashboard'
    | '/app/quality/my-tasks'
    | '/app/quality/policy-documents'
    | '/app/quality/reviews'
    | '/app/quality/training'
    | '/app/settings/audit-log'
    | '/app/settings/dashboard'
    | '/app/settings/debrief'
    | '/app/settings/parts-inventory'
    | '/app/settings/personnel'
    | '/app/settings/quality'
    | '/app/settings/tools'
    | '/app/settings/training'
    | '/app/settings/user-accounts'
    | '/app/tools/$toolId'
    | '/app/tools/archived-jobs'
    | '/app/tools/archived-tools'
    | '/app/tools/calibration'
    | '/app/tools/dashboard'
    | '/app/tools/documents'
    | '/app/tools/expense-approvals'
    | '/app/tools/my-expenses'
    | '/app/tools/my-jobs'
    | '/app/assets'
    | '/app/debrief'
    | '/app/financial'
    | '/app/management'
    | '/app/parts'
    | '/app/quality'
    | '/app/settings'
    | '/app/tools'
    | '/app/debrief/workspace/$jobId'
    | '/app/tools/jobs/$jobId'
    | '/app/tools/jobs/create'
    | '/app/tools/jobs/open'
    | '/app/tools/jobs'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/debrief'
    | '/app/financial'
    | '/app/management'
    | '/app/parts'
    | '/app/quality'
    | '/app/settings'
    | '/app/tools'
    | '/app/'
    | '/app/assets/contracts'
    | '/app/assets/contracts-dashboard'
    | '/app/assets/dashboard'
    | '/app/assets/list'
    | '/app/debrief/dashboard'
    | '/app/debrief/my-work'
    | '/app/debrief/schedule'
    | '/app/debrief/workforce'
    | '/app/financial/dashboard'
    | '/app/financial/orders'
    | '/app/financial/purchase-orders'
    | '/app/financial/service-contracts'
    | '/app/management/assets'
    | '/app/management/contracts'
    | '/app/management/debrief'
    | '/app/management/financial'
    | '/app/management/parts'
    | '/app/management/quality'
    | '/app/management/tools'
    | '/app/parts/audit'
    | '/app/parts/dashboard'
    | '/app/parts/list'
    | '/app/parts/movements'
    | '/app/quality/approvals'
    | '/app/quality/archive'
    | '/app/quality/checklists'
    | '/app/quality/dashboard'
    | '/app/quality/my-tasks'
    | '/app/quality/policy-documents'
    | '/app/quality/reviews'
    | '/app/quality/training'
    | '/app/settings/audit-log'
    | '/app/settings/dashboard'
    | '/app/settings/debrief'
    | '/app/settings/parts-inventory'
    | '/app/settings/personnel'
    | '/app/settings/quality'
    | '/app/settings/tools'
    | '/app/settings/training'
    | '/app/settings/user-accounts'
    | '/app/tools/$toolId'
    | '/app/tools/archived-jobs'
    | '/app/tools/archived-tools'
    | '/app/tools/calibration'
    | '/app/tools/dashboard'
    | '/app/tools/documents'
    | '/app/tools/expense-approvals'
    | '/app/tools/my-expenses'
    | '/app/tools/my-jobs'
    | '/app/assets/'
    | '/app/debrief/'
    | '/app/financial/'
    | '/app/management/'
    | '/app/parts/'
    | '/app/quality/'
    | '/app/settings/'
    | '/app/tools/'
    | '/app/debrief/workspace/$jobId'
    | '/app/tools/jobs/$jobId'
    | '/app/tools/jobs/create'
    | '/app/tools/jobs/open'
    | '/app/tools/jobs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/debrief': {
      id: '/app/debrief'
      path: '/debrief'
      fullPath: '/app/debrief'
      preLoaderRoute: typeof AppDebriefRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/financial': {
      id: '/app/financial'
      path: '/financial'
      fullPath: '/app/financial'
      preLoaderRoute: typeof AppFinancialRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/management': {
      id: '/app/management'
      path: '/management'
      fullPath: '/app/management'
      preLoaderRoute: typeof AppManagementRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/parts': {
      id: '/app/parts'
      path: '/parts'
      fullPath: '/app/parts'
      preLoaderRoute: typeof AppPartsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/quality': {
      id: '/app/quality'
      path: '/quality'
      fullPath: '/app/quality'
      preLoaderRoute: typeof AppQualityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tools': {
      id: '/app/tools'
      path: '/tools'
      fullPath: '/app/tools'
      preLoaderRoute: typeof AppToolsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assets/': {
      id: '/app/assets/'
      path: '/assets'
      fullPath: '/app/assets/'
      preLoaderRoute: typeof AppAssetsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assets/contracts': {
      id: '/app/assets/contracts'
      path: '/assets/contracts'
      fullPath: '/app/assets/contracts'
      preLoaderRoute: typeof AppAssetsContractsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assets/contracts-dashboard': {
      id: '/app/assets/contracts-dashboard'
      path: '/assets/contracts-dashboard'
      fullPath: '/app/assets/contracts-dashboard'
      preLoaderRoute: typeof AppAssetsContractsDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assets/dashboard': {
      id: '/app/assets/dashboard'
      path: '/assets/dashboard'
      fullPath: '/app/assets/dashboard'
      preLoaderRoute: typeof AppAssetsDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assets/list': {
      id: '/app/assets/list'
      path: '/assets/list'
      fullPath: '/app/assets/list'
      preLoaderRoute: typeof AppAssetsListRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/debrief/': {
      id: '/app/debrief/'
      path: '/'
      fullPath: '/app/debrief/'
      preLoaderRoute: typeof AppDebriefIndexRouteImport
      parentRoute: typeof AppDebriefRoute
    }
    '/app/debrief/dashboard': {
      id: '/app/debrief/dashboard'
      path: '/dashboard'
      fullPath: '/app/debrief/dashboard'
      preLoaderRoute: typeof AppDebriefDashboardRouteImport
      parentRoute: typeof AppDebriefRoute
    }
    '/app/debrief/my-work': {
      id: '/app/debrief/my-work'
      path: '/my-work'
      fullPath: '/app/debrief/my-work'
      preLoaderRoute: typeof AppDebriefMyWorkRouteImport
      parentRoute: typeof AppDebriefRoute
    }
    '/app/debrief/schedule': {
      id: '/app/debrief/schedule'
      path: '/schedule'
      fullPath: '/app/debrief/schedule'
      preLoaderRoute: typeof AppDebriefScheduleRouteImport
      parentRoute: typeof AppDebriefRoute
    }
    '/app/debrief/workforce': {
      id: '/app/debrief/workforce'
      path: '/workforce'
      fullPath: '/app/debrief/workforce'
      preLoaderRoute: typeof AppDebriefWorkforceRouteImport
      parentRoute: typeof AppDebriefRoute
    }
    '/app/financial/': {
      id: '/app/financial/'
      path: '/'
      fullPath: '/app/financial/'
      preLoaderRoute: typeof AppFinancialIndexRouteImport
      parentRoute: typeof AppFinancialRoute
    }
    '/app/financial/dashboard': {
      id: '/app/financial/dashboard'
      path: '/dashboard'
      fullPath: '/app/financial/dashboard'
      preLoaderRoute: typeof AppFinancialDashboardRouteImport
      parentRoute: typeof AppFinancialRoute
    }
    '/app/financial/orders': {
      id: '/app/financial/orders'
      path: '/orders'
      fullPath: '/app/financial/orders'
      preLoaderRoute: typeof AppFinancialOrdersRouteImport
      parentRoute: typeof AppFinancialRoute
    }
    '/app/financial/purchase-orders': {
      id: '/app/financial/purchase-orders'
      path: '/purchase-orders'
      fullPath: '/app/financial/purchase-orders'
      preLoaderRoute: typeof AppFinancialPurchaseOrdersRouteImport
      parentRoute: typeof AppFinancialRoute
    }
    '/app/financial/service-contracts': {
      id: '/app/financial/service-contracts'
      path: '/service-contracts'
      fullPath: '/app/financial/service-contracts'
      preLoaderRoute: typeof AppFinancialServiceContractsRouteImport
      parentRoute: typeof AppFinancialRoute
    }
    '/app/management/': {
      id: '/app/management/'
      path: '/'
      fullPath: '/app/management/'
      preLoaderRoute: typeof AppManagementIndexRouteImport
      parentRoute: typeof AppManagementRoute
    }
    '/app/management/assets': {
      id: '/app/management/assets'
      path: '/assets'
      fullPath: '/app/management/assets'
      preLoaderRoute: typeof AppManagementAssetsRouteImport
      parentRoute: typeof AppManagementRoute
    }
    '/app/management/contracts': {
      id: '/app/management/contracts'
      path: '/contracts'
      fullPath: '/app/management/contracts'
      preLoaderRoute: typeof AppManagementContractsRouteImport
      parentRoute: typeof AppManagementRoute
    }
    '/app/management/debrief': {
      id: '/app/management/debrief'
      path: '/debrief'
      fullPath: '/app/management/debrief'
      preLoaderRoute: typeof AppManagementDebriefRouteImport
      parentRoute: typeof AppManagementRoute
    }
    '/app/management/financial': {
      id: '/app/management/financial'
      path: '/financial'
      fullPath: '/app/management/financial'
      preLoaderRoute: typeof AppManagementFinancialRouteImport
      parentRoute: typeof AppManagementRoute
    }
    '/app/management/parts': {
      id: '/app/management/parts'
      path: '/parts'
      fullPath: '/app/management/parts'
      preLoaderRoute: typeof AppManagementPartsRouteImport
      parentRoute: typeof AppManagementRoute
    }
    '/app/management/quality': {
      id: '/app/management/quality'
      path: '/quality'
      fullPath: '/app/management/quality'
      preLoaderRoute: typeof AppManagementQualityRouteImport
      parentRoute: typeof AppManagementRoute
    }
    '/app/management/tools': {
      id: '/app/management/tools'
      path: '/tools'
      fullPath: '/app/management/tools'
      preLoaderRoute: typeof AppManagementToolsRouteImport
      parentRoute: typeof AppManagementRoute
    }
    '/app/parts/': {
      id: '/app/parts/'
      path: '/'
      fullPath: '/app/parts/'
      preLoaderRoute: typeof AppPartsIndexRouteImport
      parentRoute: typeof AppPartsRoute
    }
    '/app/parts/audit': {
      id: '/app/parts/audit'
      path: '/audit'
      fullPath: '/app/parts/audit'
      preLoaderRoute: typeof AppPartsAuditRouteImport
      parentRoute: typeof AppPartsRoute
    }
    '/app/parts/dashboard': {
      id: '/app/parts/dashboard'
      path: '/dashboard'
      fullPath: '/app/parts/dashboard'
      preLoaderRoute: typeof AppPartsDashboardRouteImport
      parentRoute: typeof AppPartsRoute
    }
    '/app/parts/list': {
      id: '/app/parts/list'
      path: '/list'
      fullPath: '/app/parts/list'
      preLoaderRoute: typeof AppPartsListRouteImport
      parentRoute: typeof AppPartsRoute
    }
    '/app/parts/movements': {
      id: '/app/parts/movements'
      path: '/movements'
      fullPath: '/app/parts/movements'
      preLoaderRoute: typeof AppPartsMovementsRouteImport
      parentRoute: typeof AppPartsRoute
    }
    '/app/quality/': {
      id: '/app/quality/'
      path: '/'
      fullPath: '/app/quality/'
      preLoaderRoute: typeof AppQualityIndexRouteImport
      parentRoute: typeof AppQualityRoute
    }
    '/app/quality/approvals': {
      id: '/app/quality/approvals'
      path: '/approvals'
      fullPath: '/app/quality/approvals'
      preLoaderRoute: typeof AppQualityApprovalsRouteImport
      parentRoute: typeof AppQualityRoute
    }
    '/app/quality/archive': {
      id: '/app/quality/archive'
      path: '/archive'
      fullPath: '/app/quality/archive'
      preLoaderRoute: typeof AppQualityArchiveRouteImport
      parentRoute: typeof AppQualityRoute
    }
    '/app/quality/checklists': {
      id: '/app/quality/checklists'
      path: '/checklists'
      fullPath: '/app/quality/checklists'
      preLoaderRoute: typeof AppQualityChecklistsRouteImport
      parentRoute: typeof AppQualityRoute
    }
    '/app/quality/dashboard': {
      id: '/app/quality/dashboard'
      path: '/dashboard'
      fullPath: '/app/quality/dashboard'
      preLoaderRoute: typeof AppQualityDashboardRouteImport
      parentRoute: typeof AppQualityRoute
    }
    '/app/quality/my-tasks': {
      id: '/app/quality/my-tasks'
      path: '/my-tasks'
      fullPath: '/app/quality/my-tasks'
      preLoaderRoute: typeof AppQualityMyTasksRouteImport
      parentRoute: typeof AppQualityRoute
    }
    '/app/quality/policy-documents': {
      id: '/app/quality/policy-documents'
      path: '/policy-documents'
      fullPath: '/app/quality/policy-documents'
      preLoaderRoute: typeof AppQualityPolicyDocumentsRouteImport
      parentRoute: typeof AppQualityRoute
    }
    '/app/quality/reviews': {
      id: '/app/quality/reviews'
      path: '/reviews'
      fullPath: '/app/quality/reviews'
      preLoaderRoute: typeof AppQualityReviewsRouteImport
      parentRoute: typeof AppQualityRoute
    }
    '/app/quality/training': {
      id: '/app/quality/training'
      path: '/training'
      fullPath: '/app/quality/training'
      preLoaderRoute: typeof AppQualityTrainingRouteImport
      parentRoute: typeof AppQualityRoute
    }
    '/app/settings/': {
      id: '/app/settings/'
      path: '/'
      fullPath: '/app/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/settings/audit-log': {
      id: '/app/settings/audit-log'
      path: '/audit-log'
      fullPath: '/app/settings/audit-log'
      preLoaderRoute: typeof AppSettingsAuditLogRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/settings/dashboard': {
      id: '/app/settings/dashboard'
      path: '/dashboard'
      fullPath: '/app/settings/dashboard'
      preLoaderRoute: typeof AppSettingsDashboardRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/settings/debrief': {
      id: '/app/settings/debrief'
      path: '/debrief'
      fullPath: '/app/settings/debrief'
      preLoaderRoute: typeof AppSettingsDebriefRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/settings/parts-inventory': {
      id: '/app/settings/parts-inventory'
      path: '/parts-inventory'
      fullPath: '/app/settings/parts-inventory'
      preLoaderRoute: typeof AppSettingsPartsInventoryRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/settings/personnel': {
      id: '/app/settings/personnel'
      path: '/personnel'
      fullPath: '/app/settings/personnel'
      preLoaderRoute: typeof AppSettingsPersonnelRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/settings/quality': {
      id: '/app/settings/quality'
      path: '/quality'
      fullPath: '/app/settings/quality'
      preLoaderRoute: typeof AppSettingsQualityRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/settings/tools': {
      id: '/app/settings/tools'
      path: '/tools'
      fullPath: '/app/settings/tools'
      preLoaderRoute: typeof AppSettingsToolsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/settings/training': {
      id: '/app/settings/training'
      path: '/training'
      fullPath: '/app/settings/training'
      preLoaderRoute: typeof AppSettingsTrainingRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/settings/user-accounts': {
      id: '/app/settings/user-accounts'
      path: '/user-accounts'
      fullPath: '/app/settings/user-accounts'
      preLoaderRoute: typeof AppSettingsUserAccountsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/tools/': {
      id: '/app/tools/'
      path: '/'
      fullPath: '/app/tools/'
      preLoaderRoute: typeof AppToolsIndexRouteImport
      parentRoute: typeof AppToolsRoute
    }
    '/app/tools/$toolId': {
      id: '/app/tools/$toolId'
      path: '/$toolId'
      fullPath: '/app/tools/$toolId'
      preLoaderRoute: typeof AppToolsToolIdRouteImport
      parentRoute: typeof AppToolsRoute
    }
    '/app/tools/archived-jobs': {
      id: '/app/tools/archived-jobs'
      path: '/archived-jobs'
      fullPath: '/app/tools/archived-jobs'
      preLoaderRoute: typeof AppToolsArchivedJobsRouteImport
      parentRoute: typeof AppToolsRoute
    }
    '/app/tools/archived-tools': {
      id: '/app/tools/archived-tools'
      path: '/archived-tools'
      fullPath: '/app/tools/archived-tools'
      preLoaderRoute: typeof AppToolsArchivedToolsRouteImport
      parentRoute: typeof AppToolsRoute
    }
    '/app/tools/calibration': {
      id: '/app/tools/calibration'
      path: '/calibration'
      fullPath: '/app/tools/calibration'
      preLoaderRoute: typeof AppToolsCalibrationRouteImport
      parentRoute: typeof AppToolsRoute
    }
    '/app/tools/dashboard': {
      id: '/app/tools/dashboard'
      path: '/dashboard'
      fullPath: '/app/tools/dashboard'
      preLoaderRoute: typeof AppToolsDashboardRouteImport
      parentRoute: typeof AppToolsRoute
    }
    '/app/tools/documents': {
      id: '/app/tools/documents'
      path: '/documents'
      fullPath: '/app/tools/documents'
      preLoaderRoute: typeof AppToolsDocumentsRouteImport
      parentRoute: typeof AppToolsRoute
    }
    '/app/tools/expense-approvals': {
      id: '/app/tools/expense-approvals'
      path: '/expense-approvals'
      fullPath: '/app/tools/expense-approvals'
      preLoaderRoute: typeof AppToolsExpenseApprovalsRouteImport
      parentRoute: typeof AppToolsRoute
    }
    '/app/tools/my-expenses': {
      id: '/app/tools/my-expenses'
      path: '/my-expenses'
      fullPath: '/app/tools/my-expenses'
      preLoaderRoute: typeof AppToolsMyExpensesRouteImport
      parentRoute: typeof AppToolsRoute
    }
    '/app/tools/my-jobs': {
      id: '/app/tools/my-jobs'
      path: '/my-jobs'
      fullPath: '/app/tools/my-jobs'
      preLoaderRoute: typeof AppToolsMyJobsRouteImport
      parentRoute: typeof AppToolsRoute
    }
    '/app/debrief/workspace/$jobId': {
      id: '/app/debrief/workspace/$jobId'
      path: '/workspace/$jobId'
      fullPath: '/app/debrief/workspace/$jobId'
      preLoaderRoute: typeof AppDebriefWorkspaceJobIdRouteImport
      parentRoute: typeof AppDebriefRoute
    }
    '/app/tools/jobs/': {
      id: '/app/tools/jobs/'
      path: '/jobs'
      fullPath: '/app/tools/jobs/'
      preLoaderRoute: typeof AppToolsJobsIndexRouteImport
      parentRoute: typeof AppToolsRoute
    }
    '/app/tools/jobs/$jobId': {
      id: '/app/tools/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/app/tools/jobs/$jobId'
      preLoaderRoute: typeof AppToolsJobsJobIdRouteImport
      parentRoute: typeof AppToolsRoute
    }
    '/app/tools/jobs/create': {
      id: '/app/tools/jobs/create'
      path: '/jobs/create'
      fullPath: '/app/tools/jobs/create'
      preLoaderRoute: typeof AppToolsJobsCreateRouteImport
      parentRoute: typeof AppToolsRoute
    }
    '/app/tools/jobs/open': {
      id: '/app/tools/jobs/open'
      path: '/jobs/open'
      fullPath: '/app/tools/jobs/open'
      preLoaderRoute: typeof AppToolsJobsOpenRouteImport
      parentRoute: typeof AppToolsRoute
    }
  }
}

interface AppDebriefRouteChildren {
  AppDebriefDashboardRoute: typeof AppDebriefDashboardRoute
  AppDebriefMyWorkRoute: typeof AppDebriefMyWorkRoute
  AppDebriefScheduleRoute: typeof AppDebriefScheduleRoute
  AppDebriefWorkforceRoute: typeof AppDebriefWorkforceRoute
  AppDebriefIndexRoute: typeof AppDebriefIndexRoute
  AppDebriefWorkspaceJobIdRoute: typeof AppDebriefWorkspaceJobIdRoute
}

const AppDebriefRouteChildren: AppDebriefRouteChildren = {
  AppDebriefDashboardRoute: AppDebriefDashboardRoute,
  AppDebriefMyWorkRoute: AppDebriefMyWorkRoute,
  AppDebriefScheduleRoute: AppDebriefScheduleRoute,
  AppDebriefWorkforceRoute: AppDebriefWorkforceRoute,
  AppDebriefIndexRoute: AppDebriefIndexRoute,
  AppDebriefWorkspaceJobIdRoute: AppDebriefWorkspaceJobIdRoute,
}

const AppDebriefRouteWithChildren = AppDebriefRoute._addFileChildren(
  AppDebriefRouteChildren,
)

interface AppFinancialRouteChildren {
  AppFinancialDashboardRoute: typeof AppFinancialDashboardRoute
  AppFinancialOrdersRoute: typeof AppFinancialOrdersRoute
  AppFinancialPurchaseOrdersRoute: typeof AppFinancialPurchaseOrdersRoute
  AppFinancialServiceContractsRoute: typeof AppFinancialServiceContractsRoute
  AppFinancialIndexRoute: typeof AppFinancialIndexRoute
}

const AppFinancialRouteChildren: AppFinancialRouteChildren = {
  AppFinancialDashboardRoute: AppFinancialDashboardRoute,
  AppFinancialOrdersRoute: AppFinancialOrdersRoute,
  AppFinancialPurchaseOrdersRoute: AppFinancialPurchaseOrdersRoute,
  AppFinancialServiceContractsRoute: AppFinancialServiceContractsRoute,
  AppFinancialIndexRoute: AppFinancialIndexRoute,
}

const AppFinancialRouteWithChildren = AppFinancialRoute._addFileChildren(
  AppFinancialRouteChildren,
)

interface AppManagementRouteChildren {
  AppManagementAssetsRoute: typeof AppManagementAssetsRoute
  AppManagementContractsRoute: typeof AppManagementContractsRoute
  AppManagementDebriefRoute: typeof AppManagementDebriefRoute
  AppManagementFinancialRoute: typeof AppManagementFinancialRoute
  AppManagementPartsRoute: typeof AppManagementPartsRoute
  AppManagementQualityRoute: typeof AppManagementQualityRoute
  AppManagementToolsRoute: typeof AppManagementToolsRoute
  AppManagementIndexRoute: typeof AppManagementIndexRoute
}

const AppManagementRouteChildren: AppManagementRouteChildren = {
  AppManagementAssetsRoute: AppManagementAssetsRoute,
  AppManagementContractsRoute: AppManagementContractsRoute,
  AppManagementDebriefRoute: AppManagementDebriefRoute,
  AppManagementFinancialRoute: AppManagementFinancialRoute,
  AppManagementPartsRoute: AppManagementPartsRoute,
  AppManagementQualityRoute: AppManagementQualityRoute,
  AppManagementToolsRoute: AppManagementToolsRoute,
  AppManagementIndexRoute: AppManagementIndexRoute,
}

const AppManagementRouteWithChildren = AppManagementRoute._addFileChildren(
  AppManagementRouteChildren,
)

interface AppPartsRouteChildren {
  AppPartsAuditRoute: typeof AppPartsAuditRoute
  AppPartsDashboardRoute: typeof AppPartsDashboardRoute
  AppPartsListRoute: typeof AppPartsListRoute
  AppPartsMovementsRoute: typeof AppPartsMovementsRoute
  AppPartsIndexRoute: typeof AppPartsIndexRoute
}

const AppPartsRouteChildren: AppPartsRouteChildren = {
  AppPartsAuditRoute: AppPartsAuditRoute,
  AppPartsDashboardRoute: AppPartsDashboardRoute,
  AppPartsListRoute: AppPartsListRoute,
  AppPartsMovementsRoute: AppPartsMovementsRoute,
  AppPartsIndexRoute: AppPartsIndexRoute,
}

const AppPartsRouteWithChildren = AppPartsRoute._addFileChildren(
  AppPartsRouteChildren,
)

interface AppQualityRouteChildren {
  AppQualityApprovalsRoute: typeof AppQualityApprovalsRoute
  AppQualityArchiveRoute: typeof AppQualityArchiveRoute
  AppQualityChecklistsRoute: typeof AppQualityChecklistsRoute
  AppQualityDashboardRoute: typeof AppQualityDashboardRoute
  AppQualityMyTasksRoute: typeof AppQualityMyTasksRoute
  AppQualityPolicyDocumentsRoute: typeof AppQualityPolicyDocumentsRoute
  AppQualityReviewsRoute: typeof AppQualityReviewsRoute
  AppQualityTrainingRoute: typeof AppQualityTrainingRoute
  AppQualityIndexRoute: typeof AppQualityIndexRoute
}

const AppQualityRouteChildren: AppQualityRouteChildren = {
  AppQualityApprovalsRoute: AppQualityApprovalsRoute,
  AppQualityArchiveRoute: AppQualityArchiveRoute,
  AppQualityChecklistsRoute: AppQualityChecklistsRoute,
  AppQualityDashboardRoute: AppQualityDashboardRoute,
  AppQualityMyTasksRoute: AppQualityMyTasksRoute,
  AppQualityPolicyDocumentsRoute: AppQualityPolicyDocumentsRoute,
  AppQualityReviewsRoute: AppQualityReviewsRoute,
  AppQualityTrainingRoute: AppQualityTrainingRoute,
  AppQualityIndexRoute: AppQualityIndexRoute,
}

const AppQualityRouteWithChildren = AppQualityRoute._addFileChildren(
  AppQualityRouteChildren,
)

interface AppSettingsRouteChildren {
  AppSettingsAuditLogRoute: typeof AppSettingsAuditLogRoute
  AppSettingsDashboardRoute: typeof AppSettingsDashboardRoute
  AppSettingsDebriefRoute: typeof AppSettingsDebriefRoute
  AppSettingsPartsInventoryRoute: typeof AppSettingsPartsInventoryRoute
  AppSettingsPersonnelRoute: typeof AppSettingsPersonnelRoute
  AppSettingsQualityRoute: typeof AppSettingsQualityRoute
  AppSettingsToolsRoute: typeof AppSettingsToolsRoute
  AppSettingsTrainingRoute: typeof AppSettingsTrainingRoute
  AppSettingsUserAccountsRoute: typeof AppSettingsUserAccountsRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsAuditLogRoute: AppSettingsAuditLogRoute,
  AppSettingsDashboardRoute: AppSettingsDashboardRoute,
  AppSettingsDebriefRoute: AppSettingsDebriefRoute,
  AppSettingsPartsInventoryRoute: AppSettingsPartsInventoryRoute,
  AppSettingsPersonnelRoute: AppSettingsPersonnelRoute,
  AppSettingsQualityRoute: AppSettingsQualityRoute,
  AppSettingsToolsRoute: AppSettingsToolsRoute,
  AppSettingsTrainingRoute: AppSettingsTrainingRoute,
  AppSettingsUserAccountsRoute: AppSettingsUserAccountsRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppToolsRouteChildren {
  AppToolsToolIdRoute: typeof AppToolsToolIdRoute
  AppToolsArchivedJobsRoute: typeof AppToolsArchivedJobsRoute
  AppToolsArchivedToolsRoute: typeof AppToolsArchivedToolsRoute
  AppToolsCalibrationRoute: typeof AppToolsCalibrationRoute
  AppToolsDashboardRoute: typeof AppToolsDashboardRoute
  AppToolsDocumentsRoute: typeof AppToolsDocumentsRoute
  AppToolsExpenseApprovalsRoute: typeof AppToolsExpenseApprovalsRoute
  AppToolsMyExpensesRoute: typeof AppToolsMyExpensesRoute
  AppToolsMyJobsRoute: typeof AppToolsMyJobsRoute
  AppToolsIndexRoute: typeof AppToolsIndexRoute
  AppToolsJobsJobIdRoute: typeof AppToolsJobsJobIdRoute
  AppToolsJobsCreateRoute: typeof AppToolsJobsCreateRoute
  AppToolsJobsOpenRoute: typeof AppToolsJobsOpenRoute
  AppToolsJobsIndexRoute: typeof AppToolsJobsIndexRoute
}

const AppToolsRouteChildren: AppToolsRouteChildren = {
  AppToolsToolIdRoute: AppToolsToolIdRoute,
  AppToolsArchivedJobsRoute: AppToolsArchivedJobsRoute,
  AppToolsArchivedToolsRoute: AppToolsArchivedToolsRoute,
  AppToolsCalibrationRoute: AppToolsCalibrationRoute,
  AppToolsDashboardRoute: AppToolsDashboardRoute,
  AppToolsDocumentsRoute: AppToolsDocumentsRoute,
  AppToolsExpenseApprovalsRoute: AppToolsExpenseApprovalsRoute,
  AppToolsMyExpensesRoute: AppToolsMyExpensesRoute,
  AppToolsMyJobsRoute: AppToolsMyJobsRoute,
  AppToolsIndexRoute: AppToolsIndexRoute,
  AppToolsJobsJobIdRoute: AppToolsJobsJobIdRoute,
  AppToolsJobsCreateRoute: AppToolsJobsCreateRoute,
  AppToolsJobsOpenRoute: AppToolsJobsOpenRoute,
  AppToolsJobsIndexRoute: AppToolsJobsIndexRoute,
}

const AppToolsRouteWithChildren = AppToolsRoute._addFileChildren(
  AppToolsRouteChildren,
)

interface AppRouteChildren {
  AppDebriefRoute: typeof AppDebriefRouteWithChildren
  AppFinancialRoute: typeof AppFinancialRouteWithChildren
  AppManagementRoute: typeof AppManagementRouteWithChildren
  AppPartsRoute: typeof AppPartsRouteWithChildren
  AppQualityRoute: typeof AppQualityRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppToolsRoute: typeof AppToolsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppAssetsContractsRoute: typeof AppAssetsContractsRoute
  AppAssetsContractsDashboardRoute: typeof AppAssetsContractsDashboardRoute
  AppAssetsDashboardRoute: typeof AppAssetsDashboardRoute
  AppAssetsListRoute: typeof AppAssetsListRoute
  AppAssetsIndexRoute: typeof AppAssetsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDebriefRoute: AppDebriefRouteWithChildren,
  AppFinancialRoute: AppFinancialRouteWithChildren,
  AppManagementRoute: AppManagementRouteWithChildren,
  AppPartsRoute: AppPartsRouteWithChildren,
  AppQualityRoute: AppQualityRouteWithChildren,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppToolsRoute: AppToolsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppAssetsContractsRoute: AppAssetsContractsRoute,
  AppAssetsContractsDashboardRoute: AppAssetsContractsDashboardRoute,
  AppAssetsDashboardRoute: AppAssetsDashboardRoute,
  AppAssetsListRoute: AppAssetsListRoute,
  AppAssetsIndexRoute: AppAssetsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
