/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppSettingsIndexRouteImport } from './routes/app.settings.index'
import { Route as AppSettingsAuditLogRouteImport } from './routes/app.settings.audit-log'
import { Route as AppSettingsDashboardRouteImport } from './routes/app.settings.dashboard'
import { Route as AppSettingsDebriefRouteImport } from './routes/app.settings.debrief'
import { Route as AppSettingsPartsInventoryRouteImport } from './routes/app.settings.parts-inventory'
import { Route as AppSettingsPersonnelRouteImport } from './routes/app.settings.personnel'
import { Route as AppSettingsQualityRouteImport } from './routes/app.settings.quality'
import { Route as AppSettingsToolsRouteImport } from './routes/app.settings.tools'
import { Route as AppSettingsTrainingRouteImport } from './routes/app.settings.training'
import { Route as AppSettingsUserAccountsRouteImport } from './routes/app.settings.user-accounts'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsAuditLogRoute = AppSettingsAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsDashboardRoute = AppSettingsDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsDebriefRoute = AppSettingsDebriefRouteImport.update({
  id: '/debrief',
  path: '/debrief',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsPartsInventoryRoute =
  AppSettingsPartsInventoryRouteImport.update({
    id: '/parts-inventory',
    path: '/parts-inventory',
    getParentRoute: () => AppSettingsRoute,
  } as any)
const AppSettingsPersonnelRoute = AppSettingsPersonnelRouteImport.update({
  id: '/personnel',
  path: '/personnel',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsQualityRoute = AppSettingsQualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsToolsRoute = AppSettingsToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsTrainingRoute = AppSettingsTrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsUserAccountsRoute = AppSettingsUserAccountsRouteImport.update({
  id: '/user-accounts',
  path: '/user-accounts',
  getParentRoute: () => AppSettingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/settings': typeof AppSettingsRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/settings/audit-log': typeof AppSettingsAuditLogRoute
  '/app/settings/dashboard': typeof AppSettingsDashboardRoute
  '/app/settings/debrief': typeof AppSettingsDebriefRoute
  '/app/settings/parts-inventory': typeof AppSettingsPartsInventoryRoute
  '/app/settings/personnel': typeof AppSettingsPersonnelRoute
  '/app/settings/quality': typeof AppSettingsQualityRoute
  '/app/settings/tools': typeof AppSettingsToolsRoute
  '/app/settings/training': typeof AppSettingsTrainingRoute
  '/app/settings/user-accounts': typeof AppSettingsUserAccountsRoute
  '/app/settings/': typeof AppSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app': typeof AppIndexRoute
  '/app/settings/audit-log': typeof AppSettingsAuditLogRoute
  '/app/settings/dashboard': typeof AppSettingsDashboardRoute
  '/app/settings/debrief': typeof AppSettingsDebriefRoute
  '/app/settings/parts-inventory': typeof AppSettingsPartsInventoryRoute
  '/app/settings/personnel': typeof AppSettingsPersonnelRoute
  '/app/settings/quality': typeof AppSettingsQualityRoute
  '/app/settings/tools': typeof AppSettingsToolsRoute
  '/app/settings/training': typeof AppSettingsTrainingRoute
  '/app/settings/user-accounts': typeof AppSettingsUserAccountsRoute
  '/app/settings': typeof AppSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/settings': typeof AppSettingsRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/settings/audit-log': typeof AppSettingsAuditLogRoute
  '/app/settings/dashboard': typeof AppSettingsDashboardRoute
  '/app/settings/debrief': typeof AppSettingsDebriefRoute
  '/app/settings/parts-inventory': typeof AppSettingsPartsInventoryRoute
  '/app/settings/personnel': typeof AppSettingsPersonnelRoute
  '/app/settings/quality': typeof AppSettingsQualityRoute
  '/app/settings/tools': typeof AppSettingsToolsRoute
  '/app/settings/training': typeof AppSettingsTrainingRoute
  '/app/settings/user-accounts': typeof AppSettingsUserAccountsRoute
  '/app/settings/': typeof AppSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/settings'
    | '/app/'
    | '/app/settings/audit-log'
    | '/app/settings/dashboard'
    | '/app/settings/debrief'
    | '/app/settings/parts-inventory'
    | '/app/settings/personnel'
    | '/app/settings/quality'
    | '/app/settings/tools'
    | '/app/settings/training'
    | '/app/settings/user-accounts'
    | '/app/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app'
    | '/app/settings/audit-log'
    | '/app/settings/dashboard'
    | '/app/settings/debrief'
    | '/app/settings/parts-inventory'
    | '/app/settings/personnel'
    | '/app/settings/quality'
    | '/app/settings/tools'
    | '/app/settings/training'
    | '/app/settings/user-accounts'
    | '/app/settings'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/settings'
    | '/app/'
    | '/app/settings/audit-log'
    | '/app/settings/dashboard'
    | '/app/settings/debrief'
    | '/app/settings/parts-inventory'
    | '/app/settings/personnel'
    | '/app/settings/quality'
    | '/app/settings/tools'
    | '/app/settings/training'
    | '/app/settings/user-accounts'
    | '/app/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings/': {
      id: '/app/settings/'
      path: '/'
      fullPath: '/app/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/settings/audit-log': {
      id: '/app/settings/audit-log'
      path: '/audit-log'
      fullPath: '/app/settings/audit-log'
      preLoaderRoute: typeof AppSettingsAuditLogRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/settings/dashboard': {
      id: '/app/settings/dashboard'
      path: '/dashboard'
      fullPath: '/app/settings/dashboard'
      preLoaderRoute: typeof AppSettingsDashboardRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/settings/debrief': {
      id: '/app/settings/debrief'
      path: '/debrief'
      fullPath: '/app/settings/debrief'
      preLoaderRoute: typeof AppSettingsDebriefRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/settings/parts-inventory': {
      id: '/app/settings/parts-inventory'
      path: '/parts-inventory'
      fullPath: '/app/settings/parts-inventory'
      preLoaderRoute: typeof AppSettingsPartsInventoryRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/settings/personnel': {
      id: '/app/settings/personnel'
      path: '/personnel'
      fullPath: '/app/settings/personnel'
      preLoaderRoute: typeof AppSettingsPersonnelRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/settings/quality': {
      id: '/app/settings/quality'
      path: '/quality'
      fullPath: '/app/settings/quality'
      preLoaderRoute: typeof AppSettingsQualityRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/settings/tools': {
      id: '/app/settings/tools'
      path: '/tools'
      fullPath: '/app/settings/tools'
      preLoaderRoute: typeof AppSettingsToolsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/settings/training': {
      id: '/app/settings/training'
      path: '/training'
      fullPath: '/app/settings/training'
      preLoaderRoute: typeof AppSettingsTrainingRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/settings/user-accounts': {
      id: '/app/settings/user-accounts'
      path: '/user-accounts'
      fullPath: '/app/settings/user-accounts'
      preLoaderRoute: typeof AppSettingsUserAccountsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
  }
}

interface AppSettingsRouteChildren {
  AppSettingsAuditLogRoute: typeof AppSettingsAuditLogRoute
  AppSettingsDashboardRoute: typeof AppSettingsDashboardRoute
  AppSettingsDebriefRoute: typeof AppSettingsDebriefRoute
  AppSettingsPartsInventoryRoute: typeof AppSettingsPartsInventoryRoute
  AppSettingsPersonnelRoute: typeof AppSettingsPersonnelRoute
  AppSettingsQualityRoute: typeof AppSettingsQualityRoute
  AppSettingsToolsRoute: typeof AppSettingsToolsRoute
  AppSettingsTrainingRoute: typeof AppSettingsTrainingRoute
  AppSettingsUserAccountsRoute: typeof AppSettingsUserAccountsRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsAuditLogRoute: AppSettingsAuditLogRoute,
  AppSettingsDashboardRoute: AppSettingsDashboardRoute,
  AppSettingsDebriefRoute: AppSettingsDebriefRoute,
  AppSettingsPartsInventoryRoute: AppSettingsPartsInventoryRoute,
  AppSettingsPersonnelRoute: AppSettingsPersonnelRoute,
  AppSettingsQualityRoute: AppSettingsQualityRoute,
  AppSettingsToolsRoute: AppSettingsToolsRoute,
  AppSettingsTrainingRoute: AppSettingsTrainingRoute,
  AppSettingsUserAccountsRoute: AppSettingsUserAccountsRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppRouteChildren {
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
